// ─── PLAN LIMITS ─────────────────────────────────────────────
export const GUEST_TONES = ["Friendly", "Playful"];
export const FREE_TONES = ["Friendly", "Playful", "Poetic", "Gen A", "Flirty"];
export const PRO_TONES = [
  "Polite", "Casual", "Sincere", "Succinct", "Assertive", "Diplomatic",
  "Empathetic", "Apologetic", "Warm", "Enthusiastic", "Urgent",
  "Shakespearean", "Professional", "Motivational", "Humble",
  "Anger", "Royal", "Luxury", "Chaotic", "Sarcastic", "Savage",
  "Overexplaining", "Dad Joke", "Rapper", "Tea",
  "Noir",
];
export const ALL_TONES = [...FREE_TONES, ...PRO_TONES];
export const DEFAULT_PRO_TONES = ["Luxury", "Poetic", "Diplomatic", "Empathetic"];
export const MAX_SAME_TONE = 3;
export const GUEST_DAILY_CAP = 10;
export const FREE_DAILY_CAP = 20;
export const PRO_DAILY_CAP = 300;
export const PRO_SAVE_LIMIT = 50;
export const PRO_SAVE_WARN = 45;
export const FREE_SAVE_LIMIT = 3;
export const FREE_BOOKMARK_LIMIT = 1;
export const PRO_BOOKMARK_LIMIT = 10;
export const PRO_SAVED_TONE_LIMIT = 5;
export const CHAR_LIMIT = 2000;
export const TONE_BLEND_DELIMITER = ":::blend:::";

export const BASE_LANGUAGES = [
  "Arabic", "Dutch", "English", "French", "German", "Italian", "Japanese",
  "Korean", "Chinese (Simplified)", "Chinese (Traditional)", "Portuguese", "Russian", "Spanish", "Vietnamese",
];
export const PRO_LANGUAGES = [
  "Amharic", "Azerbaijani", "Bengali", "Burmese", "Catalan", "Croatian",
  "Czech", "Danish", "Finnish", "Georgian", "Greek", "Gujarati", "Haitian Creole",
  "Hausa", "Hebrew", "Hindi", "Hungarian", "Indonesian", "Kazakh", "Khmer",
  "Kurdish", "Malay", "Marathi", "Mongolian", "Nepali", "Norwegian", "Persian", "Polish",
  "Punjabi", "Romanian", "Serbian", "Sinhala", "Slovak", "Swahili", "Swedish", "Tagalog",
  "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Uzbek", "Yoruba", "Zulu", "Bulgarian",
  "Albanian", "Armenian", "Belarusian", "Bosnian", "Estonian", "Icelandic", "Irish", "Latvian",
  "Lithuanian", "Macedonian", "Maltese", "Slovenian", "Assamese", "Kannada", "Malayalam", "Odia",
  "Pashto", "Syriac", "Tibetan", "Uyghur", "Lao", "Javanese", "Sundanese", "Malagasy",
  "Somali", "Xhosa", "Igbo", "Oromo", "Luganda", "Shona", "Sesotho", "Kinyarwanda",
  "Wolof", "Fula", "Aymara", "Guarani", "Quechua", "Maori", "Samoan", "Tongan",
];
export const ALL_LANGUAGES = [...BASE_LANGUAGES, ...PRO_LANGUAGES];

export const AUTO_DETECT_LANGUAGE = "Detect language";
export const DEFAULT_FROM_LANG = AUTO_DETECT_LANGUAGE;
export const DEFAULT_TO_LANG = "Korean";

export const LANGUAGE_CODE_MAP = {
  [AUTO_DETECT_LANGUAGE]: "",
  Arabic: "AR",
  Dutch: "NL",
  English: "EN",
  French: "FR",
  German: "DE",
  Italian: "IT",
  Japanese: "JA",
  Korean: "KO",
  "Chinese (Simplified)": "ZH-CN",
  "Chinese (Traditional)": "ZH-TW",
  Portuguese: "PT",
  Russian: "RU",
  Spanish: "ES",
  Vietnamese: "VI",
  Amharic: "AM",
  Azerbaijani: "AZ",
  Bengali: "BN",
  Burmese: "MY",
  Catalan: "CA",
  Croatian: "HR",
  Czech: "CS",
  Danish: "DA",
  Finnish: "FI",
  Georgian: "KA",
  Greek: "EL",
  Gujarati: "GU",
  "Haitian Creole": "HT",
  Hausa: "HA",
  Hebrew: "HE",
  Hindi: "HI",
  Hungarian: "HU",
  Indonesian: "ID",
  Kazakh: "KK",
  Khmer: "KM",
  Kurdish: "KU",
  Malay: "MS",
  Marathi: "MR",
  Mongolian: "MN",
  Nepali: "NE",
  Norwegian: "NO",
  Persian: "FA",
  Polish: "PL",
  Punjabi: "PA",
  Romanian: "RO",
  Serbian: "SR",
  Sinhala: "SI",
  Slovak: "SK",
  Swahili: "SW",
  Swedish: "SV",
  Tagalog: "TL",
  Tamil: "TA",
  Telugu: "TE",
  Thai: "TH",
  Turkish: "TR",
  Ukrainian: "UK",
  Urdu: "UR",
  Uzbek: "UZ",
  Yoruba: "YO",
  Zulu: "ZU",
  Bulgarian: "BG",
  Albanian: "SQ",
  Armenian: "HY",
  Belarusian: "BE",
  Bosnian: "BS",
  Estonian: "ET",
  Icelandic: "IS",
  Irish: "GA",
  Latvian: "LV",
  Lithuanian: "LT",
  Macedonian: "MK",
  Maltese: "MT",
  Slovenian: "SL",
  Assamese: "AS",
  Kannada: "KN",
  Malayalam: "ML",
  Odia: "OR",
  Pashto: "PS",
  Syriac: "SYC",
  Tibetan: "BO",
  Uyghur: "UG",
  Lao: "LO",
  Javanese: "JV",
  Sundanese: "SU",
  Malagasy: "MG",
  Somali: "SO",
  Xhosa: "XH",
  Igbo: "IG",
  Oromo: "OM",
  Luganda: "LG",
  Shona: "SN",
  Sesotho: "ST",
  Kinyarwanda: "RW",
  Wolof: "WO",
  Fula: "FF",
  Aymara: "AY",
  Guarani: "GN",
  Quechua: "QU",
  Maori: "MI",
  Samoan: "SM",
  Tongan: "TO",
};

const LANGUAGE_DISPLAY_OVERRIDES = {
  it: {
    [AUTO_DETECT_LANGUAGE]: "Rileva lingua",
    "Chinese (Simplified)": "Cinese (semplificato)",
    "Chinese (Traditional)": "Cinese (tradizionale)",
    "Haitian Creole": "Creolo haitiano",
  },
  pt: {
    [AUTO_DETECT_LANGUAGE]: "Detectar idioma",
    "Chinese (Simplified)": "Chinês (simplificado)",
    "Chinese (Traditional)": "Chinês (tradicional)",
    "Haitian Creole": "Crioulo haitiano",
  },
  ru: {
    [AUTO_DETECT_LANGUAGE]: "Определить язык",
    "Chinese (Simplified)": "Китайский (упрощённый)",
    "Chinese (Traditional)": "Китайский (традиционный)",
    "Haitian Creole": "Гаитянский креольский",
  },
  ar: {
    [AUTO_DETECT_LANGUAGE]: "اكتشاف اللغة",
    "Chinese (Simplified)": "الصينية (المبسطة)",
    "Chinese (Traditional)": "الصينية (التقليدية)",
    "Haitian Creole": "الكريول الهايتي",
  },
  fr: {
    [AUTO_DETECT_LANGUAGE]: "Détecter la langue",
    "Chinese (Simplified)": "Chinois (simplifié)",
    "Chinese (Traditional)": "Chinois (traditionnel)",
    "Haitian Creole": "Créole haïtien",
  },
  de: {
    [AUTO_DETECT_LANGUAGE]: "Sprache erkennen",
    "Chinese (Simplified)": "Chinesisch (vereinfacht)",
    "Chinese (Traditional)": "Chinesisch (traditionell)",
    "Haitian Creole": "Haitianisches Kreolisch",
  },
  ko: {
    [AUTO_DETECT_LANGUAGE]: "언어 감지",
    "Chinese (Simplified)": "중국어(간체)",
    "Chinese (Traditional)": "중국어(번체)",
    "Haitian Creole": "아이티 크리올어",
  },
  ja: {
    [AUTO_DETECT_LANGUAGE]: "言語を検出",
    "Chinese (Simplified)": "中国語（簡体字）",
    "Chinese (Traditional)": "中国語（繁体字）",
    "Haitian Creole": "ハイチ・クレオール語",
  },
  es: {
    [AUTO_DETECT_LANGUAGE]: "Detectar idioma",
    "Chinese (Simplified)": "Chino (simplificado)",
    "Chinese (Traditional)": "Chino (tradicional)",
    "Haitian Creole": "Criollo haitiano",
  },
  vi: {
    [AUTO_DETECT_LANGUAGE]: "Tự động nhận diện",
    "Chinese (Simplified)": "Tiếng Trung (Giản thể)",
    "Chinese (Traditional)": "Tiếng Trung (Phồn thể)",
    "Haitian Creole": "Tiếng Creole Haiti",
  },
  zh: {
    [AUTO_DETECT_LANGUAGE]: "检测语言",
    "Chinese (Simplified)": "中文（简体）",
    "Chinese (Traditional)": "中文（繁體）",
    "Haitian Creole": "海地克里奥尔语",
  },
};

const TONE_NAME_TRANSLATIONS = {
  it: {
    Friendly: "Amichevole",
    Playful: "Giocoso",
    Poetic: "Poetico",
    "Gen A": "Gen A",
    Flirty: "Civettuolo",
    Polite: "Educato",
    Casual: "Informale",
    Sincere: "Sincero",
    Succinct: "Conciso",
    Assertive: "Deciso",
    Diplomatic: "Diplomatico",
    Empathetic: "Empatico",
    Apologetic: "Mortificato",
    Warm: "Caldo",
    Enthusiastic: "Entusiasta",
    Urgent: "Urgente",
    Shakespearean: "Shakespeariano",
    Professional: "Professionale",
    Motivational: "Motivazionale",
    Humble: "Umile",
    Anger: "Arrabbiato",
    Royal: "Regale",
    Luxury: "Lussuoso",
    Chaotic: "Caotico",
    Sarcastic: "Sarcastico",
    Savage: "Tagliente",
    Overexplaining: "Troppo spiegato",
    "Dad Joke": "Battuta da papà",
    Rapper: "Rapper",
    Tea: "Pettegolo",
    Noir: "Noir",
  },
  pt: {
    Friendly: "Amigável",
    Playful: "Brincalhão",
    Poetic: "Poético",
    "Gen A": "Gen A",
    Flirty: "Flertando",
    Polite: "Educado",
    Casual: "Casual",
    Sincere: "Sincero",
    Succinct: "Conciso",
    Assertive: "Assertivo",
    Diplomatic: "Diplomático",
    Empathetic: "Empático",
    Apologetic: "Arrependido",
    Warm: "Acolhedor",
    Enthusiastic: "Entusiasmado",
    Urgent: "Urgente",
    Shakespearean: "Shakespeariano",
    Professional: "Profissional",
    Motivational: "Motivacional",
    Humble: "Humilde",
    Anger: "Com raiva",
    Royal: "Real",
    Luxury: "Luxuoso",
    Chaotic: "Caótico",
    Sarcastic: "Sarcástico",
    Savage: "Cruel",
    Overexplaining: "Explica demais",
    "Dad Joke": "Piada de pai",
    Rapper: "Rapper",
    Tea: "Fofoqueiro",
    Noir: "Noir",
  },
  ru: {
    Friendly: "Дружелюбный",
    Playful: "Игривый",
    Poetic: "Поэтичный",
    "Gen A": "Gen A",
    Flirty: "Флиртующий",
    Polite: "Вежливый",
    Casual: "Непринуждённый",
    Sincere: "Искренний",
    Succinct: "Краткий",
    Assertive: "Напористый",
    Diplomatic: "Дипломатичный",
    Empathetic: "Сочувствующий",
    Apologetic: "Извиняющийся",
    Warm: "Тёплый",
    Enthusiastic: "Воодушевлённый",
    Urgent: "Срочный",
    Shakespearean: "Шекспировский",
    Professional: "Профессиональный",
    Motivational: "Мотивирующий",
    Humble: "Скромный",
    Anger: "Злой",
    Royal: "Королевский",
    Luxury: "Роскошный",
    Chaotic: "Хаотичный",
    Sarcastic: "Саркастичный",
    Savage: "Жёсткий",
    Overexplaining: "Слишком подробно объясняющий",
    "Dad Joke": "Папина шутка",
    Rapper: "Рэперский",
    Tea: "Сплетничающий",
    Noir: "Нуар",
  },
  ar: {
    Friendly: "ودي",
    Playful: "مرح",
    Poetic: "شاعري",
    "Gen A": "Gen A",
    Flirty: "مغازل",
    Polite: "مهذب",
    Casual: "عفوي",
    Sincere: "صادق",
    Succinct: "مقتضب",
    Assertive: "حازم",
    Diplomatic: "دبلوماسي",
    Empathetic: "متعاطف",
    Apologetic: "اعتذاري",
    Warm: "دافئ",
    Enthusiastic: "متحمس",
    Urgent: "مستعجل",
    Shakespearean: "شكسبيري",
    Professional: "مهني",
    Motivational: "تحفيزي",
    Humble: "متواضع",
    Anger: "غاضب",
    Royal: "ملكي",
    Luxury: "فاخر",
    Chaotic: "فوضوي",
    Sarcastic: "ساخر",
    Savage: "لاذع",
    Overexplaining: "مبالغ في الشرح",
    "Dad Joke": "نكتة أب",
    Rapper: "رابر",
    Tea: "نمّام",
    Noir: "نوار",
  },
  fr: {
    Friendly: "Chaleureux",
    Playful: "Joueur",
    Poetic: "Poétique",
    "Gen A": "Gen A",
    Flirty: "Flirty",
    Polite: "Poli",
    Casual: "Décontracté",
    Sincere: "Sincère",
    Succinct: "Concis",
    Assertive: "Affirmé",
    Diplomatic: "Diplomate",
    Empathetic: "Empathique",
    Apologetic: "Contrit",
    Warm: "Chaud",
    Enthusiastic: "Enthousiaste",
    Urgent: "Urgent",
    Shakespearean: "Shakespearien",
    Professional: "Professionnel",
    Motivational: "Motivant",
    Humble: "Humble",
    Anger: "En colère",
    Royal: "Royal",
    Luxury: "Luxe",
    Chaotic: "Chaotique",
    Sarcastic: "Sarcastique",
    Savage: "Cinglant",
    Overexplaining: "Trop détaillé",
    "Dad Joke": "Blague de papa",
    Rapper: "Rappeur",
    Tea: "Plein de ragots",
    Noir: "Noir",
  },
  de: {
    Friendly: "Freundlich",
    Playful: "Verspielt",
    Poetic: "Poetisch",
    "Gen A": "Gen A",
    Flirty: "Flirty",
    Polite: "Höflich",
    Casual: "Locker",
    Sincere: "Aufrichtig",
    Succinct: "Knapp",
    Assertive: "Bestimmt",
    Diplomatic: "Diplomatisch",
    Empathetic: "Einfühlsam",
    Apologetic: "Reumütig",
    Warm: "Warm",
    Enthusiastic: "Begeistert",
    Urgent: "Dringend",
    Shakespearean: "Shakespearisch",
    Professional: "Professionell",
    Motivational: "Motivierend",
    Humble: "Bescheiden",
    Anger: "Wütend",
    Royal: "Königlich",
    Luxury: "Luxuriös",
    Chaotic: "Chaotisch",
    Sarcastic: "Sarkastisch",
    Savage: "Brutal",
    Overexplaining: "Übererklärend",
    "Dad Joke": "Papa-Witz",
    Rapper: "Rapper",
    Tea: "Klatschig",
    Noir: "Noir",
  },
  ko: {
    Friendly: "친근하게",
    Playful: "장난스럽게",
    Poetic: "시적으로",
    "Gen A": "Gen A",
    Flirty: "플러티하게",
    Polite: "정중하게",
    Casual: "캐주얼하게",
    Sincere: "진심 있게",
    Succinct: "간결하게",
    Assertive: "단호하게",
    Diplomatic: "외교적으로",
    Empathetic: "공감 있게",
    Apologetic: "미안하게",
    Warm: "따뜻하게",
    Enthusiastic: "열정적으로",
    Urgent: "긴급하게",
    Shakespearean: "셰익스피어풍",
    Professional: "프로답게",
    Motivational: "동기부여 있게",
    Humble: "겸손하게",
    Anger: "분노하게",
    Royal: "왕실풍",
    Luxury: "럭셔리하게",
    Chaotic: "혼돈스럽게",
    Sarcastic: "비꼬듯이",
    Savage: "독하게",
    Overexplaining: "과하게 설명하며",
    "Dad Joke": "아재개그처럼",
    Rapper: "래퍼처럼",
    Tea: "수다스럽게",
    Noir: "누아르풍",
  },
  ja: {
    Friendly: "フレンドリー",
    Playful: "遊び心",
    Poetic: "詩的",
    "Gen A": "Gen A",
    Flirty: "フラーティー",
    Polite: "丁寧",
    Casual: "カジュアル",
    Sincere: "誠実",
    Succinct: "簡潔",
    Assertive: "はっきり",
    Diplomatic: "外交的",
    Empathetic: "共感的",
    Apologetic: "申し訳なさげ",
    Warm: "あたたかい",
    Enthusiastic: "熱量高め",
    Urgent: "緊急",
    Shakespearean: "シェイクスピア風",
    Professional: "プロフェッショナル",
    Motivational: "やる気を出す",
    Humble: "控えめ",
    Anger: "怒り",
    Royal: "ロイヤル",
    Luxury: "ラグジュアリー",
    Chaotic: "カオス",
    Sarcastic: "皮肉",
    Savage: "辛辣",
    Overexplaining: "説明しすぎ",
    "Dad Joke": "ダジャレ親父",
    Rapper: "ラッパー風",
    Tea: "ゴシップ調",
    Noir: "ノワール",
  },
  es: {
    Friendly: "Amable",
    Playful: "Juguetón",
    Poetic: "Poético",
    "Gen A": "Gen A",
    Flirty: "Coqueto",
    Polite: "Cortés",
    Casual: "Casual",
    Sincere: "Sincero",
    Succinct: "Breve",
    Assertive: "Directo",
    Diplomatic: "Diplomático",
    Empathetic: "Empático",
    Apologetic: "Disculpándose",
    Warm: "Cálido",
    Enthusiastic: "Entusiasta",
    Urgent: "Urgente",
    Shakespearean: "Shakespeariano",
    Professional: "Profesional",
    Motivational: "Motivador",
    Humble: "Humilde",
    Anger: "Enojado",
    Royal: "Real",
    Luxury: "Lujo",
    Chaotic: "Caótico",
    Sarcastic: "Sarcástico",
    Savage: "Salvaje",
    Overexplaining: "Explica de más",
    "Dad Joke": "Chiste de papá",
    Rapper: "Rappero",
    Tea: "Chismoso",
    Noir: "Noir",
  },
  vi: {
    Friendly: "Thân thiện",
    Playful: "Tinh nghịch",
    Poetic: "Thi vị",
    "Gen A": "Gen A",
    Flirty: "Tán tỉnh",
    Polite: "Lịch sự",
    Casual: "Tự nhiên",
    Sincere: "Chân thành",
    Succinct: "Ngắn gọn",
    Assertive: "Quyết đoán",
    Diplomatic: "Ngoại giao",
    Empathetic: "Đồng cảm",
    Apologetic: "Xin lỗi",
    Warm: "Ấm áp",
    Enthusiastic: "Hào hứng",
    Urgent: "Khẩn cấp",
    Shakespearean: "Kiểu Shakespeare",
    Professional: "Chuyên nghiệp",
    Motivational: "Truyền động lực",
    Humble: "Khiêm tốn",
    Anger: "Giận dữ",
    Royal: "Hoàng gia",
    Luxury: "Sang trọng",
    Chaotic: "Hỗn loạn",
    Sarcastic: "Mỉa mai",
    Savage: "Cay độc",
    Overexplaining: "Giải thích quá mức",
    "Dad Joke": "Trò đùa kiểu bố",
    Rapper: "Kiểu rapper",
    Tea: "Nhiều chuyện",
    Noir: "Noir",
  },
  "zh-cn": {
    Friendly: "友好",
    Playful: "俏皮",
    Poetic: "诗意",
    "Gen A": "Gen A",
    Flirty: "暧昧",
    Polite: "礼貌",
    Casual: "随意",
    Sincere: "真诚",
    Succinct: "简洁",
    Assertive: "强势",
    Diplomatic: "圆融",
    Empathetic: "共情",
    Apologetic: "抱歉",
    Warm: "温柔",
    Enthusiastic: "热情",
    Urgent: "紧急",
    Shakespearean: "莎士比亚风",
    Professional: "专业",
    Motivational: "激励",
    Humble: "谦逊",
    Anger: "愤怒",
    Royal: "皇家",
    Luxury: "奢华",
    Chaotic: "混乱",
    Sarcastic: "讽刺",
    Savage: "毒舌",
    Overexplaining: "过度解释",
    "Dad Joke": "冷爸笑话",
    Rapper: "说唱风",
    Tea: "八卦",
    Noir: "黑色电影",
  },
  "zh-tw": {
    Friendly: "友善",
    Playful: "俏皮",
    Poetic: "詩意",
    "Gen A": "Gen A",
    Flirty: "曖昧",
    Polite: "有禮",
    Casual: "隨性",
    Sincere: "真誠",
    Succinct: "精簡",
    Assertive: "強勢",
    Diplomatic: "圓融",
    Empathetic: "有同理心",
    Apologetic: "帶歉意",
    Warm: "溫柔",
    Enthusiastic: "熱情",
    Urgent: "緊急",
    Shakespearean: "莎士比亞風",
    Professional: "專業",
    Motivational: "激勵",
    Humble: "謙遜",
    Anger: "憤怒",
    Royal: "皇家",
    Luxury: "奢華",
    Chaotic: "混亂",
    Sarcastic: "諷刺",
    Savage: "毒舌",
    Overexplaining: "過度解釋",
    "Dad Joke": "爸爸笑話",
    Rapper: "饒舌風",
    Tea: "八卦",
    Noir: "黑色電影",
  },
};

const TONE_CATEGORY_TRANSLATIONS = {
  it: {
    Everyday: "Quotidiano",
    Polished: "Rifinato",
    Heartfelt: "Sentito",
    Intense: "Intenso",
    Stylized: "Stilizzato",
    Character: "Personaggio",
  },
  pt: {
    Everyday: "Cotidiano",
    Polished: "Polido",
    Heartfelt: "Sentido",
    Intense: "Intenso",
    Stylized: "Estilizado",
    Character: "Personagem",
  },
  ru: {
    Everyday: "Повседневно",
    Polished: "Отточенно",
    Heartfelt: "С душой",
    Intense: "Резко",
    Stylized: "Стилизованно",
    Character: "С характером",
  },
  ar: {
    Everyday: "يومي",
    Polished: "مصقول",
    Heartfelt: "وجداني",
    Intense: "حاد",
    Stylized: "أسلوبي",
    Character: "شخصية",
  },
  fr: {
    Everyday: "Quotidien",
    Polished: "Soigné",
    Heartfelt: "Senti",
    Intense: "Intense",
    Stylized: "Stylisé",
    Character: "Personnage",
  },
  de: {
    Everyday: "Alltag",
    Polished: "Ausgefeilt",
    Heartfelt: "Herzlich",
    Intense: "Intensiv",
    Stylized: "Stilisiert",
    Character: "Charakter",
  },
  ko: {
    Everyday: "일상",
    Polished: "세련됨",
    Heartfelt: "진심",
    Intense: "강렬함",
    Stylized: "스타일",
    Character: "캐릭터",
  },
  ja: {
    Everyday: "日常",
    Polished: "洗練",
    Heartfelt: "気持ち重視",
    Intense: "強め",
    Stylized: "スタイル",
    Character: "キャラ",
  },
  es: {
    Everyday: "Cotidiano",
    Polished: "Pulido",
    Heartfelt: "Sentido",
    Intense: "Intenso",
    Stylized: "Con estilo",
    Character: "Personaje",
  },
  vi: {
    Everyday: "Hằng ngày",
    Polished: "Chỉn chu",
    Heartfelt: "Từ tâm",
    Intense: "Mạnh",
    Stylized: "Phong cách",
    Character: "Cá tính",
  },
  "zh-cn": {
    Everyday: "日常",
    Polished: "精致",
    Heartfelt: "走心",
    Intense: "强烈",
    Stylized: "风格化",
    Character: "角色感",
  },
  "zh-tw": {
    Everyday: "日常",
    Polished: "精緻",
    Heartfelt: "真情",
    Intense: "強烈",
    Stylized: "風格化",
    Character: "角色感",
  },
};

const TONE_DESCRIPTION_TRANSLATIONS = {
  it: {
    Polite: "Rispettoso e premuroso",
    Casual: "Rilassato e quotidiano",
    "Gen A": "Attuale e molto internet",
    Playful: "Leggero e spiritoso",
    Friendly: "Caldo e accessibile",
    Sincere: "Genuino e sentito",
    Warm: "Delicato, rassicurante e morbido",
    Succinct: "Molto breve e ridotto all'essenziale",
    Assertive: "Netto, fermo e diretto",
    Diplomatic: "Tattico ed equilibrato",
    Empathetic: "Comprensivo e premuroso",
    Apologetic: "Dispiaciuto e morbido",
    Enthusiastic: "Molto energico e animato",
    Urgent: "Immediato e pressante",
    Shakespearean: "Teatrale e da Bardo",
    Professional: "Pulito e adatto al lavoro",
    Motivational: "Carico e incoraggiante",
    Humble: "Modesto e senza ego",
    Anger: "Tagliente, acceso e apertamente arrabbiato",
    Royal: "Maestoso e regale",
    Luxury: "Elegante, costoso e raffinato",
    Chaotic: "Sregolato, folle e ingestibile",
    Sarcastic: "Tagliente e sarcastico",
    Savage: "Durissimo e spietato",
    Overexplaining: "Esagera con spiegazioni e dettagli",
    "Dad Joke": "Molto da papà e pieno di battute sceme",
    Poetic: "Lirico, evocativo e molto espressivo",
    Rapper: "Ritmico, deciso e con rime",
    Flirty: "Audace, civettuolo e allusivo",
    Tea: "Super chiacchierone e pettegolo",
    Noir: "Cupo, cinematografico e misterioso",
  },
  pt: {
    Polite: "Respeitoso e atencioso",
    Casual: "Leve e do dia a dia",
    "Gen A": "Atual e com cara de internet",
    Playful: "Leve e espirituoso",
    Friendly: "Acolhedor e simpático",
    Sincere: "Genuíno e sentido",
    Warm: "Gentil, reconfortante e suave",
    Succinct: "Muito breve e enxuto",
    Assertive: "Direto, firme e sem dúvida",
    Diplomatic: "Tático e equilibrado",
    Empathetic: "Com compreensão e cuidado",
    Apologetic: "Arrependido e suave",
    Enthusiastic: "Muito energético e animado",
    Urgent: "Imediato, pressionando e difícil de ignorar",
    Shakespearean: "Teatral e com cara de Shakespeare",
    Professional: "Limpo e seguro para o trabalho",
    Motivational: "Animador e encorajador",
    Humble: "Humilde e sem ego",
    Anger: "Afiado, quente e abertamente irritado",
    Royal: "Majestoso e real",
    Luxury: "Chique, refinado e com cara de luxo",
    Chaotic: "Descontrolado, maluco e caótico",
    Sarcastic: "Ácido e sarcástico",
    Savage: "Muito duro e sem piedade",
    Overexplaining: "Explica demais e detalha tudo",
    "Dad Joke": "Muito pai e cheio de piada ruim",
    Poetic: "Lírico, evocativo e bem expressivo",
    Rapper: "Rítmico, forte e com rimas",
    Flirty: "Ousado, sedutor e cheio de insinuação",
    Tea: "Muito falante, fofoqueiro e cheio de drama",
    Noir: "Sombrio, cinematográfico e misterioso",
  },
  ru: {
    Polite: "Вежливо и уважительно",
    Casual: "Легко и по-простому",
    "Gen A": "Современно, по-интернетному",
    Playful: "Легко и с юмором",
    Friendly: "Тепло и дружелюбно",
    Sincere: "Искренне и от души",
    Warm: "Мягко, заботливо и тепло",
    Succinct: "Очень кратко и по делу",
    Assertive: "Прямо, твёрдо и без двусмысленности",
    Diplomatic: "Тактично и взвешенно",
    Empathetic: "С пониманием и заботой",
    Apologetic: "Мягко и с извинением",
    Enthusiastic: "Очень энергично и с огоньком",
    Urgent: "Срочно, настойчиво и без промедления",
    Shakespearean: "Театрально и по-шекспировски",
    Professional: "Чисто и по-деловому",
    Motivational: "Воодушевляюще и поддерживающе",
    Humble: "Скромно и без пафоса",
    Anger: "Резко, горячо и явно зло",
    Royal: "Величаво и по-королевски",
    Luxury: "Дорого, гладко и статусно",
    Chaotic: "Безумно, рвано и неуправляемо",
    Sarcastic: "Язвительно и с колкостью",
    Savage: "Очень жёстко и беспощадно",
    Overexplaining: "Чересчур подробно и с лишними пояснениями",
    "Dad Joke": "Очень по-папиному и с корявым каламбуром",
    Poetic: "Образно, красиво и почти как строка из стиха",
    Rapper: "Ритмично, напористо и с рифмой",
    Flirty: "Смело, игриво и с намёком",
    Tea: "Очень болтливо, сочно и по-сплетнически",
    Noir: "Мрачно, кинематографично и загадочно",
  },
  ar: {
    Polite: "محترم ومراعٍ",
    Casual: "مرتاح ويومي",
    "Gen A": "أسلوب حديث بطابع الإنترنت",
    Playful: "خفيف ومرح",
    Friendly: "دافئ وسهل الاقتراب",
    Sincere: "صادق ومن القلب",
    Warm: "لطيف ومطمئن وحنون",
    Succinct: "قصير جدًا ومختصر",
    Assertive: "واضح وحازم ومباشر",
    Diplomatic: "لبق ومتوازن",
    Empathetic: "متفهم ومهتم",
    Apologetic: "نبرة اعتذار ناعمة",
    Enthusiastic: "متحمس ومليء بالطاقة",
    Urgent: "ملحّ وصعب تجاهله",
    Shakespearean: "مسرحي وبأسلوب شكسبيري",
    Professional: "نظيف وآمن للعمل",
    Motivational: "مشجع ورافع للمعنويات",
    Humble: "متواضع ومحترم",
    Anger: "حاد وغاضب بشكل واضح",
    Royal: "راقٍ وملوكي",
    Luxury: "فاخر وعالي المستوى",
    Chaotic: "منفلت وفوضوي جدًا",
    Sarcastic: "ساخر وجاف",
    Savage: "لاذع وقاسٍ جدًا",
    Overexplaining: "يفسّر بتفصيل زائد",
    "Dad Joke": "كثير التلاعب بالكلمات وبريء",
    Poetic: "غنائي ومعبر",
    Rapper: "إيقاعي وضارب وفيه قافية",
    Flirty: "لعوب وجريء ورومانسي",
    Tea: "ثرثار ومليء بالقيل والقال",
    Noir: "غامض وكئيب",
  },
  fr: {
    Polite: "Respectueux et attentionné",
    Casual: "Détendu et quotidien",
    "Gen A": "Ton très internet et actuel",
    Playful: "Léger et spirituel",
    Friendly: "Chaleureux et accessible",
    Sincere: "Authentique et touchant",
    Warm: "Doux, rassurant et tendre",
    Succinct: "Très bref et épuré",
    Assertive: "Franc, ferme et direct",
    Diplomatic: "Tactique et équilibré",
    Empathetic: "Compréhensif et attentionné",
    Apologetic: "Contrit et doux",
    Enthusiastic: "Très énergique et animé",
    Urgent: "Pressant et difficile à ignorer",
    Shakespearean: "Théâtral et à la manière du Barde",
    Professional: "Clair et sûr pour le travail",
    Motivational: "Dynamisant et encourageant",
    Humble: "Modeste et respectueux",
    Anger: "Cinglant, tendu et clairement énervé",
    Royal: "Noble et élevé",
    Luxury: "Raffiné et haut de gamme",
    Chaotic: "Très déchaîné et imprévisible",
    Sarcastic: "Sec et sarcastique",
    Savage: "Tranchant et impitoyable",
    Overexplaining: "Beaucoup trop détaillé",
    "Dad Joke": "Très ringard et plein de jeux de mots",
    Poetic: "Lyrique et expressif",
    Rapper: "Rythmique, percutant et riche en rimes",
    Flirty: "Taquin, audacieux et romantique",
    Tea: "Très bavard et plein de ragots",
    Noir: "Sombre et mystérieux",
  },
  de: {
    Polite: "Respektvoll und rücksichtsvoll",
    Casual: "Locker und alltagstauglich",
    "Gen A": "Sehr aktuell und internetgeprägt",
    Playful: "Leicht und witzig",
    Friendly: "Warm und zugänglich",
    Sincere: "Ehrlich und herzlich",
    Warm: "Sanft, beruhigend und liebevoll",
    Succinct: "Extrem kurz und reduziert",
    Assertive: "Klar, fest und direkt",
    Diplomatic: "Taktvoll und ausgewogen",
    Empathetic: "Verständnisvoll und fürsorglich",
    Apologetic: "Reumütig und weich",
    Enthusiastic: "Sehr energiegeladen und begeistert",
    Urgent: "Dringlich und schwer zu ignorieren",
    Shakespearean: "Theatralisch und bardengleich",
    Professional: "Sauber und berufssicher",
    Motivational: "Aufmunternd und motivierend",
    Humble: "Bescheiden und respektvoll",
    Anger: "Scharf, hitzig und offen wütend",
    Royal: "Erhaben und königlich",
    Luxury: "Exklusiv und hochwertig",
    Chaotic: "Extrem unhinged, wild und unberechenbar",
    Sarcastic: "Trocken und klar sarkastisch",
    Savage: "Hart, gnadenlos und brutal",
    Overexplaining: "Unnötig detailliert",
    "Dad Joke": "Peinlich, wortspielig und harmlos",
    Poetic: "Lyrisch und ausdrucksstark",
    Rapper: "Rhythmisch, punchy und reimstark",
    Flirty: "Verspielt, frech und romantisch",
    Tea: "Extra redselig und tratschig",
    Noir: "Düster und geheimnisvoll",
  },
  ko: {
    Polite: "존중하고 배려하는 톤",
    Casual: "편안하고 일상적인 톤",
    "Gen A": "요즘 인터넷 감성의 톤",
    Playful: "가볍고 재치 있는 톤",
    Friendly: "따뜻하고 다가가기 쉬운 톤",
    Sincere: "진솔하고 진심 어린 톤",
    Warm: "부드럽고 안심되는 다정한 톤",
    Succinct: "아주 짧고 군더더기 없는 톤",
    Assertive: "단호하고 분명한 톤",
    Diplomatic: "신중하고 균형 잡힌 톤",
    Empathetic: "이해심 있고 배려하는 톤",
    Apologetic: "미안함이 드러나는 부드러운 톤",
    Enthusiastic: "에너지 넘치고 신나는 톤",
    Urgent: "즉각적이고 다급한 톤",
    Shakespearean: "극적이고 셰익스피어풍인 톤",
    Professional: "깔끔하고 업무에 안전한 톤",
    Motivational: "힘을 실어주고 북돋는 톤",
    Humble: "겸손하고 공손한 톤",
    Anger: "날카롭고 화가 난 톤",
    Royal: "품위 있고 고급스러운 톤",
    Luxury: "고급스럽고 하이엔드한 톤",
    Chaotic: "매우 정신없고 거친 톤",
    Sarcastic: "건조하고 비꼬는 톤",
    Savage: "날카롭고 잔인할 만큼 센 톤",
    Overexplaining: "불필요할 정도로 자세한 톤",
    "Dad Joke": "말장난이 많은 아재개그 톤",
    Poetic: "서정적이고 표현적인 톤",
    Rapper: "리듬감 있고 라임이 느껴지는 톤",
    Flirty: "대담하게 장난스럽고 로맨틱한 톤",
    Tea: "유난히 수다스럽고 가십 같은 톤",
    Noir: "어둡고 미스터리한 톤",
  },
  ja: {
    Polite: "敬意があり思いやりのあるトーン",
    Casual: "気楽で日常的なトーン",
    "Gen A": "今っぽいネット感のあるトーン",
    Playful: "軽くてウィットのあるトーン",
    Friendly: "やさしく親しみやすいトーン",
    Sincere: "本気でまっすぐなトーン",
    Warm: "やわらかく安心感のあるトーン",
    Succinct: "かなり短く削ぎ落としたトーン",
    Assertive: "はっきりしていて迷いのないトーン",
    Diplomatic: "配慮がありバランスの取れたトーン",
    Empathetic: "理解があり寄り添うトーン",
    Apologetic: "申し訳なさが伝わるやわらかいトーン",
    Enthusiastic: "かなり元気で盛り上がったトーン",
    Urgent: "急ぎで見過ごしにくいトーン",
    Shakespearean: "芝居がかっていてシェイクスピア風のトーン",
    Professional: "きれいで仕事向きのトーン",
    Motivational: "前向きで背中を押すトーン",
    Humble: "控えめで礼儀正しいトーン",
    Anger: "鋭く怒りがにじむトーン",
    Royal: "高貴で気品のあるトーン",
    Luxury: "上質でラグジュアリーなトーン",
    Chaotic: "かなり暴走気味で予測不能なトーン",
    Sarcastic: "乾いていて皮肉の効いたトーン",
    Savage: "鋭く容赦ないトーン",
    Overexplaining: "必要以上に細かいトーン",
    "Dad Joke": "だじゃれ多めの親父ギャグ調トーン",
    Poetic: "叙情的で表現豊かなトーン",
    Rapper: "リズム感があり韻を踏むトーン",
    Flirty: "大胆でからかうようなロマンチックなトーン",
    Tea: "かなりおしゃべりでゴシップっぽいトーン",
    Noir: "ムーディーでミステリアスなトーン",
  },
  es: {
    Polite: "Respetuoso y considerado",
    Casual: "Relajado y cotidiano",
    "Gen A": "Tono actual y de internet",
    Playful: "Ligero e ingenioso",
    Friendly: "Cálido y cercano",
    Sincere: "Genuino y de corazón",
    Warm: "Suave, reconfortante y afectuoso",
    Succinct: "Muy breve y reducido al mínimo",
    Assertive: "Claro, firme y directo",
    Diplomatic: "Cuidadoso y equilibrado",
    Empathetic: "Comprensivo y atento",
    Apologetic: "Arrepentido y suave",
    Enthusiastic: "Muy energético, emocionado y expresivo",
    Urgent: "Inmediato y difícil de ignorar",
    Shakespearean: "Teatral y shakespeariano",
    Professional: "Limpio y adecuado para trabajo",
    Motivational: "Animado y muy alentador",
    Humble: "Modesto y respetuoso",
    Anger: "Cortante, intenso y claramente molesto",
    Royal: "Regio y elevado",
    Luxury: "Elegante y de alto nivel",
    Chaotic: "Muy descontrolado, errático y salvaje",
    Sarcastic: "Seco, mordaz y claramente sarcástico",
    Savage: "Filoso, despiadado y brutal",
    Overexplaining: "Demasiado detallado",
    "Dad Joke": "Muy cursi, lleno de juegos de palabras e inocente",
    Poetic: "Lírico y expresivo",
    Rapper: "Rítmico, potente y con rima",
    Flirty: "Juguetón, atrevido y romántico",
    Tea: "Muy conversador, jugoso y chismoso",
    Noir: "Oscuro y misterioso",
  },
  vi: {
    Polite: "Lịch sự và biết điều",
    Casual: "Thoải mái và đời thường",
    "Gen A": "Đậm chất internet hiện đại",
    Playful: "Nhẹ nhàng và dí dỏm",
    Friendly: "Ấm áp và dễ gần",
    Sincere: "Chân thành và thật lòng",
    Warm: "Dịu dàng, trấn an và mềm mại",
    Succinct: "Rất ngắn gọn và tối giản",
    Assertive: "Rõ ràng, chắc chắn và thẳng thắn",
    Diplomatic: "Khéo léo và cân bằng",
    Empathetic: "Thấu hiểu và quan tâm",
    Apologetic: "Nhẹ nhàng mang ý xin lỗi",
    Enthusiastic: "Rất giàu năng lượng và hào hứng",
    Urgent: "Gấp gáp và khó bỏ qua",
    Shakespearean: "Kịch tính theo kiểu Shakespeare",
    Professional: "Gọn gàng và phù hợp công việc",
    Motivational: "Khích lệ và nâng tinh thần",
    Humble: "Khiêm tốn và tôn trọng",
    Anger: "Sắc, nóng và rõ sự bực tức",
    Royal: "Cao quý và sang trọng",
    Luxury: "Đẳng cấp và cao cấp",
    Chaotic: "Rất mất kiểm soát và điên loạn",
    Sarcastic: "Khô khan và mỉa mai rõ rệt",
    Savage: "Sắc bén, tàn nhẫn và cực gắt",
    Overexplaining: "Giải thích quá mức cần thiết",
    "Dad Joke": "Sến, nhiều chơi chữ và vô hại",
    Poetic: "Trữ tình và giàu biểu cảm",
    Rapper: "Có nhịp điệu, lực và vần",
    Flirty: "Tinh nghịch, táo bạo và lãng mạn",
    Tea: "Cực nhiều chuyện và đầy tính buôn dưa",
    Noir: "U tối và bí ẩn",
  },
  "zh-cn": {
    Polite: "尊重、体贴",
    Casual: "轻松、日常",
    "Gen A": "很新潮、很网感",
    Playful: "轻快又俏皮",
    Friendly: "温暖、好接近",
    Sincere: "真诚、发自内心",
    Warm: "温柔、安抚、情绪柔和",
    Succinct: "极其简短、非常精炼",
    Assertive: "直接、坚定、不含糊",
    Diplomatic: "圆融、平衡、有分寸",
    Empathetic: "理解你、很会共情",
    Apologetic: "带歉意、语气柔和",
    Enthusiastic: "非常有能量、很兴奋",
    Urgent: "很急、很有压迫感",
    Shakespearean: "戏剧化、莎士比亚风",
    Professional: "干净利落、适合职场",
    Motivational: "打鸡血、很鼓舞人",
    Humble: "谦逊、礼貌",
    Anger: "尖锐、火大、明显带怒气",
    Royal: "高贵、气场强",
    Luxury: "高级、奢华",
    Chaotic: "非常疯、非常乱",
    Sarcastic: "干冷、明显在讽刺",
    Savage: "犀利、狠、毫不留情",
    Overexplaining: "解释得过于详细",
    "Dad Joke": "很土但无害的冷笑话风",
    Poetic: "有诗意、表达丰富",
    Rapper: "有节奏、有冲击力、带押韵",
    Flirty: "大胆、撩人、带暧昧",
    Tea: "超爱聊、很八卦",
    Noir: "阴郁、神秘",
  },
  "zh-tw": {
    Polite: "尊重又有分寸",
    Casual: "輕鬆、日常",
    "Gen A": "很新潮、很有網感",
    Playful: "輕快又俏皮",
    Friendly: "溫暖、好接近",
    Sincere: "真誠、發自內心",
    Warm: "溫柔、安撫、情緒柔和",
    Succinct: "非常精簡、毫不拖泥帶水",
    Assertive: "直接、堅定、不含糊",
    Diplomatic: "圓融、平衡、有分寸",
    Empathetic: "很懂你、很有同理心",
    Apologetic: "帶歉意、語氣柔和",
    Enthusiastic: "很有能量、很興奮",
    Urgent: "很急、很難忽視",
    Shakespearean: "戲劇化、莎士比亞風",
    Professional: "乾淨俐落、適合職場",
    Motivational: "很鼓舞、很打氣",
    Humble: "謙遜、有禮",
    Anger: "尖銳、火大、明顯帶怒氣",
    Royal: "高貴、有氣場",
    Luxury: "高級、奢華",
    Chaotic: "非常失控、非常瘋",
    Sarcastic: "乾冷、明顯在諷刺",
    Savage: "犀利、狠、毫不留情",
    Overexplaining: "解釋得過於詳細",
    "Dad Joke": "很冷但無害的爸爸笑話感",
    Poetic: "有詩意、很有表達感",
    Rapper: "有節奏、有力、帶押韻",
    Flirty: "大膽、撩人、帶曖昧",
    Tea: "超愛聊、很八卦",
    Noir: "陰鬱、神秘",
  },
};

export function getLanguageCode(label) {
  const value = String(label || "").trim();
  if (!value) return "";
  if (LANGUAGE_CODE_MAP[value]) return LANGUAGE_CODE_MAP[value];
  const normalized = value.toLowerCase();
  const matched = Object.entries(LANGUAGE_CODE_MAP).find(([name]) => name.toLowerCase() === normalized);
  if (matched) return matched[1];
  if (/detect|auto/i.test(value)) return "";
  return value.slice(0, 2).toUpperCase();
}

export function getLocalizedLanguageName(label, locale = "en") {
  const resolvedLocale = String(locale || "en").toLowerCase().slice(0, 2);
  const overrides = LANGUAGE_DISPLAY_OVERRIDES[resolvedLocale];
  if (overrides?.[label]) return overrides[label];
  if (!label || resolvedLocale === "en") return label;

  const rawCode = LANGUAGE_CODE_MAP[label];
  if (!rawCode) return label;

  const normalizedCode = rawCode.toLowerCase();
  try {
    const display = new Intl.DisplayNames([resolvedLocale], { type: "language" });
    const localized = display.of(normalizedCode);
    return localized || label;
  } catch {
    return label;
  }
}

export function getLocalizedToneName(tone, locale = "en") {
  const resolvedLocale = String(locale || "en").toLowerCase().slice(0, 2);
  return TONE_NAME_TRANSLATIONS[resolvedLocale]?.[tone] || tone;
}

export function getLocalizedToneCategory(label, locale = "en") {
  const resolvedLocale = String(locale || "en").toLowerCase().slice(0, 2);
  return TONE_CATEGORY_TRANSLATIONS[resolvedLocale]?.[label] || label;
}

export function getLocalizedToneDescription(tone, locale = "en") {
  const resolvedLocale = String(locale || "en").toLowerCase().slice(0, 2);
  return TONE_DESCRIPTION_TRANSLATIONS[resolvedLocale]?.[tone] || TONE_DESCRIPTIONS[tone] || "";
}

export const TONE_CATEGORIES = [
  { label: "Everyday", tones: ["Friendly", "Playful", "Casual", "Gen A", "Flirty"] },
  { label: "Polished", tones: ["Polite", "Professional", "Diplomatic", "Succinct", "Assertive", "Luxury"] },
  { label: "Heartfelt", tones: ["Empathetic", "Sincere", "Warm", "Apologetic", "Humble", "Motivational"] },
  { label: "Intense", tones: ["Urgent", "Anger", "Savage", "Noir"] },
  { label: "Stylized", tones: ["Poetic", "Rapper", "Shakespearean", "Royal", "Sarcastic"] },
  { label: "Character", tones: ["Chaotic", "Tea", "Overexplaining", "Dad Joke", "Enthusiastic"] },
];

export const TONE_DESCRIPTIONS = {
  Polite: "Respectful and considerate",
  Casual: "Relaxed and everyday",
  "Gen A": "Current, internet-native tone",
  Playful: "Light and witty",
  Friendly: "Warm and approachable",
  Sincere: "Genuine and heartfelt",
  Warm: "Gentle, reassuring, and emotionally soft",
  Succinct: "Extremely brief and stripped down",
  Assertive: "Blunt, firm, and unmistakably direct",
  Diplomatic: "Tactful and balanced",
  Empathetic: "Understanding and caring",
  Apologetic: "Remorseful and soft",
  Enthusiastic: "Very energetic, excited, and animated",
  Urgent: "Immediate, pressing, and hard to ignore",
  Shakespearean: "Theatrical and Bard-like",
  Professional: "Clean and corporate-safe",
  Motivational: "Hyped, uplifting, and strongly encouraging",
  Humble: "Deferential and respectful",
  Anger: "Sharp, heated, and openly pissed off",
  Royal: "Regal and elevated",
  Luxury: "Elevated and high-end",
  Chaotic: "Extremely unhinged, erratic, and wild",
  Sarcastic: "Dry, cutting, and clearly sarcastic",
  Savage: "Sharp, ruthless, and extra brutal",
  Overexplaining: "Needlessly detailed",
  "Dad Joke": "Maximum cornball, pun-heavy, and harmless",
  Poetic: "Lyrical and expressive",
  Rapper: "Rhythmic, punchy, and rhyme-forward",
  Flirty: "Boldly playful, teasing, and romantic",
  Tea: "Extra chatty, juicy, and unapologetically gossipy",
  Noir: "Moody and mysterious",
};

function getBlendPairKey(a, b) {
  return [a, b].filter(Boolean).sort().join("||");
}

const WARN_BLEND_PAIRS = new Set([
  getBlendPairKey("Professional", "Chaotic"),
  getBlendPairKey("Diplomatic", "Chaotic"),
  getBlendPairKey("Luxury", "Chaotic"),
  getBlendPairKey("Royal", "Gen A"),
  getBlendPairKey("Shakespearean", "Gen A"),
  getBlendPairKey("Savage", "Dad Joke"),
  getBlendPairKey("Apologetic", "Dad Joke"),
  getBlendPairKey("Noir", "Dad Joke"),
  getBlendPairKey("Sarcastic", "Humble"),
  getBlendPairKey("Urgent", "Dad Joke"),
]);

const BLOCK_BLEND_PAIRS = new Set([
  getBlendPairKey("Succinct", "Overexplaining"),
  getBlendPairKey("Professional", "Chaotic"),
]);

export function getBlendToneState(mainTone, blendTone) {
  if (!mainTone || !blendTone || mainTone === blendTone) return "allowed";
  const key = getBlendPairKey(mainTone, blendTone);
  if (BLOCK_BLEND_PAIRS.has(key)) return "blocked";
  if (WARN_BLEND_PAIRS.has(key)) return "warn";
  return "allowed";
}

export function serializeToneSelection(mainTone, blendTone = null) {
  if (!blendTone) return mainTone || null;
  return `${mainTone}${TONE_BLEND_DELIMITER}${blendTone}`;
}

export function parseToneSelection(value) {
  if (!value || typeof value !== "string" || !value.includes(TONE_BLEND_DELIMITER)) {
    return { tone: value || null, blendTone: null };
  }
  const [tone, blendTone] = value.split(TONE_BLEND_DELIMITER);
  return { tone: tone || null, blendTone: blendTone || null };
}

export function getUserTier(user, isPremium) {
  if (!user) return "guest";
  return isPremium ? "pro" : "free";
}

export function getCapForTier(userTier) {
  if (userTier === "pro") return PRO_DAILY_CAP;
  if (userTier === "free") return FREE_DAILY_CAP;
  return GUEST_DAILY_CAP;
}

export function getBookmarkLimitForTier(userTier) {
  return userTier === "pro" ? PRO_BOOKMARK_LIMIT : userTier === "free" ? FREE_BOOKMARK_LIMIT : 0;
}

export function getUnlockedTones(userTier) {
  if (userTier === "pro") return ALL_TONES;
  if (userTier === "free") return FREE_TONES;
  return GUEST_TONES;
}

export function getToneStatus(tone, userTier) {
  if (getUnlockedTones(userTier).includes(tone)) return "unlocked";
  if (FREE_TONES.includes(tone)) return "free_locked";
  return "pro_locked";
}

// ─── THEMES ──────────────────────────────────────────────────
export const THEMES = {
  dark: {
    bg:"#060606", phoneBg:"#0c0c0c", surface:"#161616", surface2:"#1e1e1e", surface3:"#121212",
    border:"#2a2a2a", border2:"#383838", borderLight:"#202020",
    text:"#f0ece0", textMuted:"#cac6ba", textDim:"#a7a39d", textFaint:"#97938c",
    accent:"#c8f0a0", accentText:"#0a1a00", accentDim:"#72a852",
    highlight:"#0c1c0c", highlightBorder:"#2a4a2a", highlightText:"#b8e090",
    highlight2:"#0a1810", highlightBorder2:"#1e3828", highlightText2:"#90c878",
    notch:"#181818", proTag:"#d4b040", freeTag:"#5a98e0",
    cOk:"#97938c", cWarn:"#d4b040", cCrit:"#c86060",
    inputBg:"#101010",
  },
  light: {
    bg:"#e4e0d6", phoneBg:"#f8f4ef", surface:"#eeeae0", surface2:"#e4e0d6", surface3:"#f2eee4",
    border:"#cac6ba", border2:"#aea8a0", borderLight:"#dedad0",
    text:"#1a180e", textMuted:"#3a3828", textDim:"#5a5848", textFaint:"#7a7868",
    accent:"#2a7020", accentText:"#f0ece0", accentDim:"#3a8a30",
    highlight:"#daeeda", highlightBorder:"#7ab87a", highlightText:"#1a401a",
    highlight2:"#e4f0e0", highlightBorder2:"#90c890", highlightText2:"#204020",
    notch:"#d8d4c8", proTag:"#d4b040", freeTag:"#1a5890",
    cOk:"#7a7868", cWarn:"#906010", cCrit:"#a83030",
    inputBg:"#f2ede4",
  },
};
